#!/bin/bash
#
# chkconfig: - 92 08
# processname: reporting-producer
# config: /etc/reporting-producer/config.yaml
# pidfile: /var/run/reporting-producer/reporting-producer.pid
# description: reporting producer is a daemon to collect data and send to the server
#
### BEGIN INIT INFO
# Provides: reporting-producer
# Required-Start: $local_fs $remote_fs
# Required-Stop: $local_fs $remote_fs
# Should-Start: $time $network $syslog iptables firehol shorewall ferm
# Should-Stop: $network $syslog iptables firehol shorewall ferm
# Default-Start: 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start/Stop reporting-producer
# Description: Start/Stop reporting-producer, a daemon to collect data and send to the server
### END INIT INFO

CONFIG_FILE="/etc/reporting-producer/config.yaml"
PRODUCER_LOCATION="/opt/producers"
prog="reporting-producer"
exec_name="producer.py"
MAINPROG="$PRODUCER_LOCATION/$exec_name"
pidfile=${PIDFILE-/var/run/reporting-producer/reporting-producer.pid}
RUN_AS="producer"

system=unknown
if [ -f /etc/redhat-release ]; then
    system=redhat
elif [ -f /etc/system-release ]; then
    system=redhat
elif [ -f /etc/debian_version ]; then
    system=debian
fi

if [ "$system" = "redhat" ]; then
    ## source platform specific external scripts
    . /etc/init.d/functions
    [ -r /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

    ## set or override platform specific variables
    lockfile=${LOCKFILE-/var/lock/subsys/$prog}

    echo_ok() {
        echo_success; echo
    }
    echo_fail() {
        echo_failure; echo
    }
    log_success_msg() {
        success $"$@"
    }
    log_failure_msg() {
        failure $"$@"
        echo $"$@"
    }
    log_action_msg() {
        echo $@
    }
fi

if [ "$system" = "debian" ]; then
    ## source platform specific external scripts
    . /lib/lsb/init-functions
    [ -r /etc/default/$prog ] && . /etc/default/$prog

    ## set or override platform specific variables
    lockfile=${LOCKFILE-/var/lock/$prog}

    echo_ok() {
        log_end_msg 0
    }
    echo_fail() {
        log_end_msg 1
    }
fi

RETVAL=0

# Check that the config file exists
[ -f $CONFIG_FILE ] || exit 0

ensure_dir() {
    if [ ! -d $1 ]; then
        mkdir -p $1
        chown -R $2 $1
        chmod 755 $1
    fi
}

start() {

    [ -x ${MAINPROG} ] || exit 5

    status &> /dev/null

    if [ $? -eq 0 ]; then
        log_action_msg "$prog is already running."
        echo_ok
        exit 0
    fi

    ensure_dir /var/run/reporting-producer $RUN_AS
    ensure_dir /var/lib/reporting-producer $RUN_AS
    ensure_dir /var/log/reporting-producer $RUN_AS
    echo -n $"Starting reporting producer: "
    sudo -u $RUN_AS ${MAINPROG} -c $CONFIG_FILE -p $pidfile -b > /dev/null
    RETVAL=$?
    if [ $RETVAL = 0 ]; then
        touch ${lockfile}
	echo_ok
    else
        echo_fail
    fi
    echo
    return $RETVAL
}

stop() {
    echo -n $"Stopping reporting producer: "
    sudo -u $RUN_AS ${MAINPROG} -c $CONFIG_FILE -p $pidfile -k > /dev/null
    RETVAL=$?
    if [ $RETVAL = 0 ]; then
        rm -f ${lockfile} ${pidfile}
        echo_ok
    else
        echo_fail
    fi
    echo
    return $RETVAL
}

status() {
    local pid

    # First try "ps"
    pid=$(pgrep -P1 -fl $exec_name | grep -v grep | grep -v bash | cut -f1 -d" ")
    if [ -n "$pid" ]; then
        log_action_msg $"${prog} (pid $pid) is running..."
        return 0
    fi

    # Next try "/var/run/*.pid" files
    if [ -f "$pidfile" ] ; then
        read pid < "$pidfile"
        if [ -n "$pid" ]; then
            log_action_msg $"${prog} dead but pid file exists"
            return 1
        fi
    fi

    # See if $lockfile
    if [ -f "$lockfile" ]; then
        log_action_msg $"${prog} dead but subsys locked"
        return 2
    fi

    log_action_msg $"${prog} is stopped"
    return 3
}

# See how we were called.
case "$1" in
    start)
        status -p ${pidfile} ${exec_name} >/dev/null 2>&1 && exit 0
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status -p ${pidfile} ${exec_name}
        RETVAL=$?
        if [ $RETVAL -ne 0 ]; then
            if [ -f $pidfile ]; then
                echo $"$prog has exited unexpectedly."
	    fi
        fi
        ;;
    *)
        echo $"Usage: reporting-producer {start|stop|restart|status}"
        RETVAL=2
esac

exit $RETVAL
